zomato:
  outputs:
    dev:
      account: 
      database: ZOMATO
      password: 
      role: DBT_ROLE
      schema: STAGING
      threads: 1
      type: snowflake
      user: 
      warehouse: ZOMATO_WH
  target: dev
