-- Step 3 — External stage on S3 + CSV file format
USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO;
USE SCHEMA RAW;

-- create rule
CREATE OR REPLACE FILE FORMAT ZOMATO.RAW.CSV_FMT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = (' ', '\\N','NULL')
    TRIM_SPACE = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- Upload one CSV per folder.
CREATE OR REPLACE STAGE ZOMATO.RAW.ZOMATO_RAW_STAGE
    STORAGE_INTEGRATION = ZOMATO_S3_INT
    URL = 's3://dt-zomato-pipeline-dl/raw/'
    FILE_FORMAT = ZOMATO.RAW.CSV_FMT;
-- Check run 
LIST @ZOMATO.RAW.ZOMATO_RAW_STAGE